name: CI

on: [push]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
  node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: NPM Install
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: npm install, build, and test
      run: npm ci
      env:
        CI: true

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the image
        run: docker-compose build